### ISSUE TITLE
Cannot login to admin interface after installing chart

### ISSUE THREAD

**Issue by Ahmadre** [shyim/shopware-chart#3]
At first: thank you sooo much for this great chart and all in all shopware itself ❤️

If I install the chart everything works fine and MySQL and Redis are ready and connected.

But we encountered after installing the chart, that we cannot login to the admin interface on `myshopware.com/admin`

we just set in the values.yaml for this:

```yaml
shopware:
  ...
  install:
    adminUsername: "user"
    adminPassword: "password"
  ...
```

But we can't login with `user` and `password`.

Edit:
What's also weird is that the url is changed to: `myshopware.com/admin#/login`
